name: Docker Image CI pdns-mysql 4.5 alpine

on:
  push:
    tags:
      - 'pdns-mysql-alpine-4.5'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push PDNS
        id: docker_build_pdns
        uses: docker/build-push-action@v2
        with:
          context: ./pdns
          platforms: linux/amd64,linux/arm64
          file: ./pdns/Dockerfile.alpine
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pdns-mysql:4.5-alpine

      - name: Image digest
        run: echo ${{ steps.docker_build_pdns.outputs.digest }}
